<a href="https://colab.research.google.com/github/PragyaAnanth/WorldStatisticsAnalysis/blob/main/CB_SC_I5DAS18027_DataViz_Case_Study_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **18CS312 - Data Visualization**
# **Analysis of World Statistics â€” A Case Study Project**

**Faculty:** <br>
Ms. Archanaa R <br>
Assistent Professor <br>
Department of Computer Science and Engineering <br>
Amrita School of Engineering Coimbatore <br>
<br>

**Student Details:** 
### **Pragya Ananth**
### **CB.SC.I5DAS18027**
Integrated M.Sc. Data Science <br>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/18CSC312 - Data Visualization/Project Case Study/data.csv')
df.head()

  Country Name  ... Surface area (sq. km)
0  Afghanistan  ...                   NaN
1  Afghanistan  ...              652860.0
2  Afghanistan  ...              652860.0
3  Afghanistan  ...              652860.0
4  Afghanistan  ...              652860.0

[5 rows x 55 columns]

In [ ]:
df.shape

(16104, 55)

In [ ]:
df['Country Name'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Caribbean small states', 'Cayman Islands',
       'Central African Republic', 'Central Europe and the Baltics',
       'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Early-demographic dividend', 'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Ecuador',
       'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD countries)', 'European Union',
       'Faroe Islands', 'Fiji', 'Finland',
       'Fragile and conflict affected situations', 'France',
       'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only',
       'Iceland', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Korea, Dem. Peopleâ€™s Rep.', 'Korea, Rep.', 'Kosovo', 'Kuwait',
       'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia',
       'Least developed countries: UN classification', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North America', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Not classified',
       'OECD members', 'Oman', 'Other small states',
       'Pacific island small states', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Post-demographic dividend',
       'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Small states', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain',
       'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Martin (French part)', 'St. Vincent and the Grenadines',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)',
       'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [ ]:
df.columns

Index(['Country Name', 'Country Code', 'year',
       'Access to electricity (% of population)',
       'Access to electricity, rural (% of rural population)',
       'Agricultural irrigated land (% of total agricultural land)',
       'Agricultural land (% of land area)', 'Agricultural land (sq. km)',
       'Agricultural machinery, tractors',
       'Agricultural machinery, tractors per 100 sq. km of arable land',
       'Agricultural methane emissions (% of total)',
       'Agricultural methane emissions (thousand metric tons of CO2 equivalent)',
       'Agricultural nitrous oxide emissions (% of total)',
       'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)',
       'Agricultural raw materials exports (% of merchandise exports)',
       'Agricultural raw materials imports (% of merchandise imports)',
       'Agriculture, forestry, and fishing, value added (% of GDP)',
       'Agriculture, forestry, and fishing, value added (current US$)',
       'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)',
       'Arable land (% of land area)', 'Arable land (hectares per person)',
       'Arable land (hectares)',
       'Average precipitation in depth (mm per year)',
       'Birth rate, crude (per 1,000 people)',
       'Cereal production (metric tons)', 'Cereal yield (kg per hectare)',
       'CPIA gender equality rating (1=low to 6=high)',
       'Crop production index (2004-2006 = 100)',
       'Death rate, crude (per 1,000 people)',
       'Employment in agriculture (% of total employment) (modeled ILO estimate)',
       'Employment in agriculture, female (% of female employment) (modeled ILO estimate)',
       'Employment in agriculture, male (% of male employment) (modeled ILO estimate)',
       'Fertilizer consumption (% of fertilizer production)',
       'Fertilizer consumption (kilograms per hectare of arable land)',
       'Food production index (2004-2006 = 100)',
       'Forest area (% of land area)', 'Forest area (sq. km)',
       'GDP per capita (current US$)', 'Land area (sq. km)',
       'Land under cereal production (hectares)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Livestock production index (2004-2006 = 100)',
       'Mineral rents (% of GDP)',
       'Mortality rate, infant (per 1,000 live births)', 'Net migration',
       'Permanent cropland (% of land area)', 'Population, total',
       'Rural land area (sq. km)',
       'Rural land area where elevation is below 5 meters (% of total land area)',
       'Rural land area where elevation is below 5 meters (sq. km)',
       'Rural population', 'Rural population (% of total population)',
       'Rural population growth (annual %)',
       'Rural population living in areas where elevation is below 5 meters (% of total population)',
       'Surface area (sq. km)'],
      dtype='object')

In [ ]:
df.isnull().sum()

Country Name                                                                                      0
Country Code                                                                                      0
year                                                                                              0
Access to electricity (% of population)                                                        9930
Access to electricity, rural (% of rural population)                                          10145
Agricultural irrigated land (% of total agricultural land)                                    15248
Agricultural land (% of land area)                                                             3049
Agricultural land (sq. km)                                                                     2872
Agricultural machinery, tractors                                                               8321
Agricultural machinery, tractors per 100 sq. km of arable land                                 8680
Agricultural methane emissions (% of total)                                                    6389
Agricultural methane emissions (thousand metric tons of CO2 equivalent)                        5584
Agricultural nitrous oxide emissions (% of total)                                              6350
Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)                  5584
Agricultural raw materials exports (% of merchandise exports)                                  7135
Agricultural raw materials imports (% of merchandise imports)                                  7107
Agriculture, forestry, and fishing, value added (% of GDP)                                     6410
Agriculture, forestry, and fishing, value added (current US$)                                  6468
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                 15468
Arable land (% of land area)                                                                   3186
Arable land (hectares per person)                                                              3212
Arable land (hectares)                                                                         5591
Average precipitation in depth (mm per year)                                                  14036
Birth rate, crude (per 1,000 people)                                                           1589
Cereal production (metric tons)                                                                4285
Cereal yield (kg per hectare)                                                                  4323
CPIA gender equality rating (1=low to 6=high)                                                 14366
Crop production index (2004-2006 = 100)                                                        3534
Death rate, crude (per 1,000 people)                                                           1612
Employment in agriculture (% of total employment) (modeled ILO estimate)                       9114
Employment in agriculture, female (% of female employment) (modeled ILO estimate)              9114
Employment in agriculture, male (% of male employment) (modeled ILO estimate)                  9114
Fertilizer consumption (% of fertilizer production)                                           14279
Fertilizer consumption (kilograms per hectare of arable land)                                 13117
Food production index (2004-2006 = 100)                                                        3420
Forest area (% of land area)                                                                   9247
Forest area (sq. km)                                                                           9211
GDP per capita (current US$)                                                                   3735
Land area (sq. km)                                                                             1169
Land under cereal production (hectares)                                                        4312
Literacy rate, adult total (% of people ages 15 and above)                                    13600
Livestock production index (2004-2006 = 100)                                                   3455
Mineral rents (% of GDP)                                                                       5267
Mortality rate, infant (per 1,000 live births)                                                 4269
Net migration                                                                                 13236
Permanent cropland (% of land area)                                                            3760
Population, total                                                                               433
Rural land area (sq. km)                                                                      15429
Rural land area where elevation is below 5 meters (% of total land area)                      15435
Rural land area where elevation is below 5 meters (sq. km)                                    15429
Rural population                                                                                553
Rural population (% of total population)                                                        512
Rural population growth (annual %)                                                             1257
Rural population living in areas where elevation is below 5 meters (% of total population)    15429
Surface area (sq. km)                                                                          1169
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16104 entries, 0 to 16103
Data columns (total 55 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Country Name                                                                                16104 non-null  object
 1   Country Code                                                                                16104 non-null  object
 2   year                                                                                        16104 non-null  int64
 3   Access to electricity (% of population)                                                     6174 non-null   float64
 4   Access to electricity, rural (% of rural population)                                        5959 non-null   float64
 5   Agricultural irrigated land (% of total agricultural land)                                  856 non-null    float64
 6   Agricultural land (% of land area)                                                          13055 non-null  float64
 7   Agricultural land (sq. km)                                                                  13232 non-null  float64
 8   Agricultural machinery, tractors                                                            7783 non-null   float64
 9   Agricultural machinery, tractors per 100 sq. km of arable land                              7424 non-null   float64
 10  Agricultural methane emissions (% of total)                                                 9715 non-null   float64
 11  Agricultural methane emissions (thousand metric tons of CO2 equivalent)                     10520 non-null  float64
 12  Agricultural nitrous oxide emissions (% of total)                                           9754 non-null   float64
 13  Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)               10520 non-null  float64
 14  Agricultural raw materials exports (% of merchandise exports)                               8969 non-null   float64
 15  Agricultural raw materials imports (% of merchandise imports)                               8997 non-null   float64
 16  Agriculture, forestry, and fishing, value added (% of GDP)                                  9694 non-null   float64
 17  Agriculture, forestry, and fishing, value added (current US$)                               9636 non-null   float64
 18  Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)               636 non-null    float64
 19  Arable land (% of land area)                                                                12918 non-null  float64
 20  Arable land (hectares per person)                                                           12892 non-null  float64
 21  Arable land (hectares)                                                                      10513 non-null  float64
 22  Average precipitation in depth (mm per year)                                                2068 non-null   float64
 23  Birth rate, crude (per 1,000 people)                                                        14515 non-null  float64
 24  Cereal production (metric tons)                                                             11819 non-null  float64
 25  Cereal yield (kg per hectare)                                                               11781 non-null  float64
 26  CPIA gender equality rating (1=low to 6=high)                                               1738 non-null   float64
 27  Crop production index (2004-2006 = 100)                                                     12570 non-null  float64
 28  Death rate, crude (per 1,000 people)                                                        14492 non-null  float64
 29  Employment in agriculture (% of total employment) (modeled ILO estimate)                    6990 non-null   float64
 30  Employment in agriculture, female (% of female employment) (modeled ILO estimate)           6990 non-null   float64
 31  Employment in agriculture, male (% of male employment) (modeled ILO estimate)               6990 non-null   float64
 32  Fertilizer consumption (% of fertilizer production)                                         1825 non-null   float64
 33  Fertilizer consumption (kilograms per hectare of arable land)                               2987 non-null   float64
 34  Food production index (2004-2006 = 100)                                                     12684 non-null  float64
 35  Forest area (% of land area)                                                                6857 non-null   float64
 36  Forest area (sq. km)                                                                        6893 non-null   float64
 37  GDP per capita (current US$)                                                                12369 non-null  float64
 38  Land area (sq. km)                                                                          14935 non-null  float64
 39  Land under cereal production (hectares)                                                     11792 non-null  float64
 40  Literacy rate, adult total (% of people ages 15 and above)                                  2504 non-null   float64
 41  Livestock production index (2004-2006 = 100)                                                12649 non-null  float64
 42  Mineral rents (% of GDP)                                                                    10837 non-null  float64
 43  Mortality rate, infant (per 1,000 live births)                                              11835 non-null  float64
 44  Net migration                                                                               2868 non-null   float64
 45  Permanent cropland (% of land area)                                                         12344 non-null  float64
 46  Population, total                                                                           15671 non-null  float64
 47  Rural land area (sq. km)                                                                    675 non-null    float64
 48  Rural land area where elevation is below 5 meters (% of total land area)                    669 non-null    float64
 49  Rural land area where elevation is below 5 meters (sq. km)                                  675 non-null    float64
 50  Rural population                                                                            15551 non-null  float64
 51  Rural population (% of total population)                                                    15592 non-null  float64
 52  Rural population growth (annual %)                                                          14847 non-null  float64
 53  Rural population living in areas where elevation is below 5 meters (% of total population)  675 non-null    float64
 54  Surface area (sq. km)                                                                       14935 non-null  float64
dtypes: float64(52), int64(1), object(2)
memory usage: 6.8+ MB

In [ ]:
df.fillna(value=0,inplace=True)

In [ ]:
df.head()

  Country Name  ... Surface area (sq. km)
0  Afghanistan  ...                   0.0
1  Afghanistan  ...              652860.0
2  Afghanistan  ...              652860.0
3  Afghanistan  ...              652860.0
4  Afghanistan  ...              652860.0

[5 rows x 55 columns]

In [ ]:
df.isnull().sum()

Country Name                                                                                  0
Country Code                                                                                  0
year                                                                                          0
Access to electricity (% of population)                                                       0
Access to electricity, rural (% of rural population)                                          0
Agricultural irrigated land (% of total agricultural land)                                    0
Agricultural land (% of land area)                                                            0
Agricultural land (sq. km)                                                                    0
Agricultural machinery, tractors                                                              0
Agricultural machinery, tractors per 100 sq. km of arable land                                0
Agricultural methane emissions (% of total)                                                   0
Agricultural methane emissions (thousand metric tons of CO2 equivalent)                       0
Agricultural nitrous oxide emissions (% of total)                                             0
Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)                 0
Agricultural raw materials exports (% of merchandise exports)                                 0
Agricultural raw materials imports (% of merchandise imports)                                 0
Agriculture, forestry, and fishing, value added (% of GDP)                                    0
Agriculture, forestry, and fishing, value added (current US$)                                 0
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                 0
Arable land (% of land area)                                                                  0
Arable land (hectares per person)                                                             0
Arable land (hectares)                                                                        0
Average precipitation in depth (mm per year)                                                  0
Birth rate, crude (per 1,000 people)                                                          0
Cereal production (metric tons)                                                               0
Cereal yield (kg per hectare)                                                                 0
CPIA gender equality rating (1=low to 6=high)                                                 0
Crop production index (2004-2006 = 100)                                                       0
Death rate, crude (per 1,000 people)                                                          0
Employment in agriculture (% of total employment) (modeled ILO estimate)                      0
Employment in agriculture, female (% of female employment) (modeled ILO estimate)             0
Employment in agriculture, male (% of male employment) (modeled ILO estimate)                 0
Fertilizer consumption (% of fertilizer production)                                           0
Fertilizer consumption (kilograms per hectare of arable land)                                 0
Food production index (2004-2006 = 100)                                                       0
Forest area (% of land area)                                                                  0
Forest area (sq. km)                                                                          0
GDP per capita (current US$)                                                                  0
Land area (sq. km)                                                                            0
Land under cereal production (hectares)                                                       0
Literacy rate, adult total (% of people ages 15 and above)                                    0
Livestock production index (2004-2006 = 100)                                                  0
Mineral rents (% of GDP)                                                                      0
Mortality rate, infant (per 1,000 live births)                                                0
Net migration                                                                                 0
Permanent cropland (% of land area)                                                           0
Population, total                                                                             0
Rural land area (sq. km)                                                                      0
Rural land area where elevation is below 5 meters (% of total land area)                      0
Rural land area where elevation is below 5 meters (sq. km)                                    0
Rural population                                                                              0
Rural population (% of total population)                                                      0
Rural population growth (annual %)                                                            0
Rural population living in areas where elevation is below 5 meters (% of total population)    0
Surface area (sq. km)                                                                         0
dtype: int64

In [ ]:
#df.to_csv('/content/drive/MyDrive/18CSC312 - Data Visualization/Project Case Study/data_clean.csv')

In [ ]:
df1=df.loc[(df["Country Name"]=="Brazil") | (df["Country Name"]=="India")]
df1

     Country Name  ... Surface area (sq. km)
1647       Brazil  ...          0.000000e+00
1648       Brazil  ...          8.515770e+06
1649       Brazil  ...          8.515770e+06
1650       Brazil  ...          8.515770e+06
1651       Brazil  ...          8.515770e+06
...           ...  ...                   ...
6705        India  ...          3.287259e+06
6706        India  ...          3.287259e+06
6707        India  ...          3.287259e+06
6708        India  ...          0.000000e+00
6709        India  ...          0.000000e+00

[122 rows x 55 columns]

In [ ]:
df1["Country Name2"]=df1["Country Name"].map({"India":1,"Brazil":2})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df1

     Country Name Country Code  ...  Surface area (sq. km)  Country Name2
1647       Brazil          BRA  ...           0.000000e+00              2
1648       Brazil          BRA  ...           8.515770e+06              2
1649       Brazil          BRA  ...           8.515770e+06              2
1650       Brazil          BRA  ...           8.515770e+06              2
1651       Brazil          BRA  ...           8.515770e+06              2
...           ...          ...  ...                    ...            ...
6705        India          IND  ...           3.287259e+06              1
6706        India          IND  ...           3.287259e+06              1
6707        India          IND  ...           3.287259e+06              1
6708        India          IND  ...           0.000000e+00              1
6709        India          IND  ...           0.000000e+00              1

[122 rows x 56 columns]

In [ ]:
dims=["Agriculture, forestry, and fishing, value added (% of GDP)",
      "Agricultural raw materials exports (% of merchandise exports)",
    'Agricultural raw materials imports (% of merchandise imports)']

In [ ]:
fig=px.parallel_coordinates(df1,color="Country Name2",labels={"Country Name2":"Country"},dimensions=dims,
                            color_continuous_scale=px.colors.diverging.Tealrose)
                             #color_continuous_midpoint=2)
fig.show(renderer='colab')

In [ ]:
df11=df.loc[df["Country Name"]=="India"]

In [ ]:
dims1=[  'Access to electricity (% of population)',
       'Access to electricity, rural (% of rural population)',
       'Agricultural machinery, tractors']

In [ ]:
fig1 = px.scatter_matrix(df11,dimensions=dims1,color="year")
fig1.update_yaxes(automargin=True,tickangle=45)
fig1.update_xaxes(automargin=True,tickangle=45)
fig1.show(renderer='colab')